### ISSUE TITLE
How to replace Foundation with Bootstrap?

### ISSUE THREAD

**Issue by ciases** [mohamdio/gulp-workflow#1]
Hello there!
As I see `bower.json` contains both foundation and bootstrap dependencies. And `index.html` includes `foundation-site.css` by default (not bootstrap styles). So the question is: how can I change Foundation with Bootstrap? Where is this magic option? I look for it but without success.
Thanks!

**Comment by mohamdio** [comment]
Hi, 
**First**: if you need more options depend on the workflow you can use this [ [Slush-Kickstart](https://github.com/mohamdio/slush-kickstart) ] which have more options when you start your workflow.

**Second**: if you want to just change this default foundation framework, please do that : 
in this file [ [gulp/paths.js](https://github.com/mohamdio/gulp-workflow/blob/master/gulp/paths.js#L36) ] just change this code : 
`'!' + src + 'scss/vendor/bootstrap.scss'`
to:
`'!' + src + 'scss/vendor/foundation-sites.scss'`

**Third**: if you want to completely remove foundation and using enough bootstrap, please do that : 
1. remove foundation from here : [bower.js](https://github.com/mohamdio/gulp-workflow/blob/master/bower.json#L20) & [here](https://github.com/mohamdio/gulp-workflow/blob/master/bower.json#L33)
2. remove this code : 
`path.to.sass.foundation,`
from here : [gulp/config.js](https://github.com/mohamdio/gulp-workflow/blob/master/gulp/config.js#L93)
3. in this file [ [gulp/paths.js](https://github.com/mohamdio/gulp-workflow/blob/master/gulp/paths.js#L36) ] : remove this codes : 
`'!' + src + 'scss/vendor/bootstrap.scss'`
`foundation: src + 'scss/vendor/lib/foundation-sites/scss',`

**Comment by ciases** [comment]
Thanks for the detailed response! :+1:
