### ISSUE TITLE
SASS task stuck

### ISSUE THREAD

**Issue by JakubKontra** [mohamdio/gulp-workflow#2]
Hi, thanks for your stack, but i got some errors.

Everytime i have changed my scss files, your task get stucked.

Command: 
`gulp`

Thanks!
<img width="816" alt="screen shot 2017-01-25 at 16 02 42" src="https://cloud.githubusercontent.com/assets/479276/22295472/5fbd7116-e317-11e6-82b8-df271bc04ebb.png">

**Comment by mohamdio** [comment]
I updated the workflow and this issue should be solved now.
